### ISSUE TITLE
Examples and docs say angular-raven but its actually ngRaven

### ISSUE THREAD

**Issue by deweydb** [umurkontaci/angular-raven#2]
title says it all.

**Comment by danilo-valente** [comment]
The docs are correct, and if you check angular-raven.js you will find this line:
`var ngRaven = angular.module("angular-raven", []);`

I had the same issue when I installed by `bower install angular-raven`, but then I found out that the angular-raven package on bower actually links to [this](https://github.com/gdi2290/angular-raven) project, which is the one that exposes a `ngRaven` module.

**Comment by umurkontaci** [comment]
It's not `ngRaven` actually, it is `angular-raven`, `ng` prefix is reserved for angular team and we're not supposed to add any items with `ng` prefix as it can collide with something else in the future. `angular-raven` is more appropriate.

I know I am using `ngRaven` in the code but it is not exposed to anywhere else, therefore it's unlikely to be a problem.
